begin;
create extension if not exists pgtap with schema extensions;
select plan(17);
select has_table('public','currency_transfers','currency payout transfers exist');
select has_pk('public','currency_transfers','currency transfers have a primary key');
select has_column('public','currency_transfers','status','transfers track review status');
select has_column('public','currency_transfers','created_at','transfers use one displayed date');
select hasnt_column('public','currency_transfers','reviewed_at','transfers do not duplicate review dates');
select hasnt_column('public','currency_transfers','updated_at','transfers do not store an unused update date');
select has_trigger('public','currency_transfers','currency_transfers_review','transfer review workflow exists');
select col_type_is('public','currency_transfers','status','request_status','transfers reuse request status enum');
select has_check('public','currency_transfers','currency transfers have database checks');
select ok((select relrowsecurity from pg_class where oid='public.currency_transfers'::regclass),'currency transfers use RLS');
select policies_are('public','currency_transfers',array['currency_transfers_owner_read'],'users only read their transfers');
select has_function('public','request_currency_transfer',array['text','numeric','text','text','text','text','text','text','text','text','text','text','text','text','text','text'],'transfer request RPC exists');
select has_function('public','review_currency_transfer',array['uuid','text','text'],'transfer review RPC exists');
select ok(has_function_privilege('authenticated','public.request_currency_transfer(text,numeric,text,text,text,text,text,text,text,text,text,text,text,text,text,text)','EXECUTE'),'users can request transfers');
select ok(not has_function_privilege('authenticated','public.review_currency_transfer(uuid,text,text)','EXECUTE'),'users cannot review transfers');
select ok(not has_table_privilege('authenticated','public.currency_transfers','INSERT'),'users cannot bypass request RPC');
select ok(not has_table_privilege('authenticated','public.currency_transfers','UPDATE'),'users cannot approve transfers');
select * from finish();
rollback;
